# Automatically merge non-functional Dependabot updates, which means anything but Castle.Core.
# All dependencies other than Castle.Core are either test frameworks or style/quality libraries.

name: Auto merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR
        if: contains(steps.metadata.outputs.dependency-names, 'Castle.Core') == false
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: contains(steps.metadata.outputs.dependency-names, 'Castle.Core') == false
        run: gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
